micronaut:
  application:
  name: order-service
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
    connectionTimeout: 100000
    poolName: order-service-hikari-connection-pool
    maximumPoolSize: 100

endpoints:
  metrics:
    enabled: true
    sensitive: false